name: Yellow Kite
favicon: null
layout_spectrum: 0.9679784446489066
typography_spectrum: 0.88819310371764
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.04870603675954044
  lightness: 0.9745775710325688
  saturation: 0.21421659737825394
  rhythmicContrast: 0.40098424907773733
purpose: []
